name: Terraform Apply (Reusable)

on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        default: "1.16.0"

      aws_region:
        type: string
        required: true

      working_directory:
        type: string
        required: true

      environment:
        type: string
        required: true

      runs_on:
        type: string
        default: ubuntu-latest

      s3_backend_bucket:
        type: string
        required: true

      s3_backend_key:
        type: string
        required: true

    secrets:
      OIDC_ROLE_ARN:
        required: true
      TF_VAR_EXTRAS:
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Apply Terraform (${{ inputs.environment }})
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.environment }}

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ inputs.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ inputs.s3_backend_bucket }}" \
            -backend-config="key=${{ inputs.s3_backend_key }}" \
            -backend-config="region=${{ inputs.aws_region }}" \
            -backend-config="encrypt=true" \
            -input=false

      # --------------------
      # Inject TF vars from map
      # --------------------
      - name: Export TF_VAR_EXTRAS to env
        run: |
          if [ -n "${TF_VAR_EXTRAS}" ]; then
            echo "$TF_VAR_EXTRAS" | jq -r 'to_entries|map("TF_VAR_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
          fi
        env:
          TF_VAR_EXTRAS: ${{ secrets.TF_VAR_EXTRAS }}

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
